[profile.default]
src = "src"
out = "foundry-out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"

[fmt]
line_length = 100
multiline_func_header = "params_first"
